@base_url = http://localhost:8000

POST {{base_url}}/locations
Content-Type: application/json

{
  "lat": 12.34,
  "long": 56.78
}
###

POST {{base_url}}/question
Content-Type: application/json

{
  "question": "Hola?",
  "answer_type": "text",
  "options": ["1", "2"]
}
###

