// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: forms.sql

package dbgen

import (
	"context"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (question, answer_type, options)
VALUES ($1, $2, $3)
RETURNING id, question, answer_type, options
`

type CreateQuestionParams struct {
	Question   string
	AnswerType string
	Options    []string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, arg.Question, arg.AnswerType, arg.Options)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.AnswerType,
		&i.Options,
	)
	return i, err
}
