// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: locations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (lat, long) VALUES ($1, $2) RETURNING id, lat, long
`

type CreateLocationParams struct {
	Lat  pgtype.Numeric
	Long pgtype.Numeric
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Lat, arg.Long)
	var i Location
	err := row.Scan(&i.ID, &i.Lat, &i.Long)
	return i, err
}

const getAllLocationsByUser = `-- name: GetAllLocationsByUser :many
SELECT l.id, l.lat, l.long FROM locations l
JOIN locations_users ON locations_users.location_id = locations.id 
WHERE users_id = $1
`

func (q *Queries) GetAllLocationsByUser(ctx context.Context, usersID int64) ([]Location, error) {
	rows, err := q.db.Query(ctx, getAllLocationsByUser, usersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.ID, &i.Lat, &i.Long); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
