// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: locations.sql

package dbgen

import (
	"context"
)

const getAllLocationsByUser = `-- name: GetAllLocationsByUser :many
SELECT l.id, l.lat, l.long FROM locations l
JOIN locations_users ON locations_users.location_id = locations.id 
WHERE users_id = $1
`

func (q *Queries) GetAllLocationsByUser(ctx context.Context, usersID int64) ([]Location, error) {
	rows, err := q.db.Query(ctx, getAllLocationsByUser, usersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.ID, &i.Lat, &i.Long); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
