// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Location struct {
	ID   int64
	Lat  int64
	Long int64
}

type LocationsUser struct {
	LocationID int64
	UsersID    int64
}

type User struct {
	ID    int64
	Name  string
	Admin pgtype.Bool
}
