// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	ID          int64
	Name        string
	Description string
}

type FormsQuestion struct {
	FormID     int64
	QuestionID int64
}

type Location struct {
	ID   int64
	Lat  pgtype.Numeric
	Long pgtype.Numeric
}

type LocationsUser struct {
	LocationID int64
	UsersID    int64
}

type Question struct {
	ID         int64
	Question   string
	AnswerType string
	Options    []string
}

type User struct {
	ID    int64
	Name  string
	Admin pgtype.Bool
}
