// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerType string

const (
	AnswerTypeText           AnswerType = "text"
	AnswerTypeNumber         AnswerType = "number"
	AnswerTypeMultipleChoice AnswerType = "multiple_choice"
	AnswerTypeSingleChoice   AnswerType = "single_choice"
)

func (e *AnswerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnswerType(s)
	case string:
		*e = AnswerType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnswerType: %T", src)
	}
	return nil
}

type NullAnswerType struct {
	AnswerType AnswerType
	Valid      bool // Valid is true if AnswerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnswerType) Scan(value interface{}) error {
	if value == nil {
		ns.AnswerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnswerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnswerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnswerType), nil
}

type Answer struct {
	ID         int64
	Value      string
	FormID     int64
	QuestionID int64
}

type Form struct {
	ID          int64
	Name        string
	Description string
}

type FormsQuestion struct {
	FormID     int64
	QuestionID int64
	Required   bool
	DependsOn  pgtype.Int8
}

type Location struct {
	ID   int64
	Lat  pgtype.Numeric
	Long pgtype.Numeric
}

type LocationsUser struct {
	LocationID int64
	UsersID    int64
}

type Option struct {
	ID    int64
	Value string
}

type Question struct {
	ID         int64
	Question   string
	AnswerType AnswerType
}

type QuestionOption struct {
	OptionID   int64
	QuestionID int64
}

type User struct {
	ID    int64
	Name  string
	Admin pgtype.Bool
}
